services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile.ssr
    container_name: protolab-portfolio
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - bunkerweb-net
    labels:
      - "bunkerweb.SERVER_NAME=protolab.ovh www.protolab.ovh"
      - "bunkerweb.USE_REVERSE_PROXY=yes"
      - "bunkerweb.REVERSE_PROXY_URL=/"
      - "bunkerweb.REVERSE_PROXY_HOST=http://protolab-portfolio:4321"

networks:
  bunkerweb-net:
    external: true